# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
