# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160515_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
