# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20160522_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='updated_date',
            new_name='last_updated_date',
        ),
    ]
