# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
