# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
