# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160522_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='short_name',
            new_name='short_code',
        ),
    ]
