# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20160607_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='civil-war-movie', max_length=85, unique=True),
            preserve_default=False,
        ),
    ]
