# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20160608_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_crew',
            field=models.ManyToManyField(through='movies.movie_artist', to='movies.artist'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='movies.movie_genre', to='movies.genre'),
        ),
    ]
